--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender
--Q2. Which customers used a discount but still spent more than the average purchase amount? 
 
select customer_id, discount_applied, purchase_amount
from customer
where discount_applied= 'Yes' and purchase_amount >= (select(avg(purchase_amount)) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

select category, avg(review_rating)
from customer
group by category
order by avg(review_rating) limit 5 


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select avg(purchase_amount) as avg_purchase_amt, shipping_type
from customer
where shipping_type = 'Express' or shipping_type = 'Standard'
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status, round(avg(purchase_amount),2) as avg_pur_amnt, round(sum(purchase_amount),2) as tot_pur_amnt
from customer
group by subscription_status
order by avg_pur_amnt desc


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, round(100* sum(case when discount_applied='Yes' then 1 else 0 end)/count(*) ,2) as perc_discount
from customer 
group by item_purchased
order by perc_discount desc limit 5 

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

select Count(*) as total_count,
case 
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10  then 'Returning'
when previous_purchases >= 11  then 'Loyal'
end as "customer segment" 
from customer
group by "customer segment"
order by total_count desc

--Q8. What are the top 3 most purchased products within each category? 

with item_counts as(
select category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category	order by count(customer_id) desc ) as item_rank
from customer
group by category , item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank < 4;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as count_cust
from customer
where previous_purchases >5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 

select * from customer limit 20 


select age_group, sum(purchase_amount)
from customer
group by age_group
order by sum(purchase_amount) desc